"""Shared test fixtures."""

from __future__ import annotations

import os
import select
import subprocess
import sys
import time
import traceback
from pathlib import Path
from typing import IO, TYPE_CHECKING, Any

import pytest

from pidprobe import _snapshot as snapshot_module
from pidprobe._envelope import Envelope

if TYPE_CHECKING:
    from collections.abc import Callable, Iterator
    from types import FrameType

TARGETS_DIR = Path(__file__).parent / "targets"
READY_TIMEOUT_SECONDS = 10.0
KILL_TIMEOUT_SECONDS = 5.0


def _test_process_frames() -> dict[int, FrameType]:
    """Stand in for the injected script's ``_pidprobe_target_frames`` helper."""
    return dict(sys._current_frames())  # noqa: SLF001 -- the injected script uses it too


def run_collector_source(source: str) -> dict[str, Any]:
    """Run injected collector source in this process and return its payload.

    ``sys.remote_exec`` needs a live target and, on macOS, root; running the
    generated source here instead exercises the collectors themselves on every
    platform. The source is generated by pidprobe, so nothing untrusted is
    executed.
    """
    namespace: dict[str, Any] = {
        "_pidprobe_sys": sys,
        "_pidprobe_traceback": traceback,
        "_pidprobe_target_frames": _test_process_frames,
    }
    exec(source, namespace)  # noqa: S102 -- pidprobe generated this source itself
    payload: dict[str, Any] = namespace["payload"]
    return payload


def _wait_for_ready(stream: IO[str], timeout: float) -> None:
    """Block until the target prints its READY line, or fail the test.

    Uses select() instead of a blocking readline() so a target that never
    starts fails fast instead of hanging CI.
    """
    deadline = time.monotonic() + timeout
    while True:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            pytest.fail(f"target process did not print READY within {timeout}s")
        ready, _, _ = select.select([stream], [], [], remaining)
        if not ready:
            continue
        line = stream.readline()
        if line == "":
            pytest.fail("target process exited before printing READY")
        if line.strip() == "READY":
            return


@pytest.fixture
def local_target(monkeypatch: pytest.MonkeyPatch) -> dict[str, Any]:
    """Run the injected source in this process instead of a remote target.

    Returns a dict that records what the channel was asked to do, so tests can
    assert on the arguments ``take_snapshot`` passed on.
    """
    calls: dict[str, Any] = {}

    def fake_execute(pid: int, source: str, **kwargs: Any) -> Envelope:
        calls.update(pid=pid, source=source, **kwargs)
        return Envelope(status="ok", error=None, payload=run_collector_source(source))

    monkeypatch.setattr(snapshot_module, "execute_in_target", fake_execute)
    return calls


@pytest.fixture
def spawn_target() -> Iterator[Callable[[str], subprocess.Popen[str]]]:
    """Return a factory that starts a target from ``tests/targets``.

    The factory blocks until the target printed READY, so tests never race
    against interpreter start-up, and every spawned process is killed during
    teardown even when the test fails.
    """
    processes: list[subprocess.Popen[str]] = []

    def _spawn(name: str) -> subprocess.Popen[str]:
        # A build-time opt-out on the developer machine must not leak into
        # the target, or sys.remote_exec would be refused for the wrong
        # reason.
        env = os.environ.copy()
        env.pop("PYTHON_DISABLE_REMOTE_DEBUG", None)
        proc = subprocess.Popen(  # noqa: S603 -- fixed, trusted argv; no shell
            [sys.executable, str(TARGETS_DIR / f"{name}.py")],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            env=env,
        )
        processes.append(proc)
        assert proc.stdout is not None
        _wait_for_ready(proc.stdout, READY_TIMEOUT_SECONDS)
        return proc

    yield _spawn

    for proc in processes:
        if proc.poll() is None:
            proc.kill()
        proc.wait(timeout=KILL_TIMEOUT_SECONDS)


@pytest.fixture
def remote_exec_supported() -> None:
    """Skip the test unless this machine can actually inject code."""
    if not hasattr(sys, "remote_exec"):
        pytest.skip("sys.remote_exec is not available (requires CPython 3.14+)")
    if sys.platform == "darwin" and os.geteuid() != 0:
        pytest.skip("requires root on macOS (task_for_pid)")
