"""Generation of the script that pidprobe injects into the target process.

:func:`sys.remote_exec` runs a *file* in the target's main thread at the next
bytecode boundary, using only the target's own interpreter. The generated
script therefore has to be standalone (standard library only) and defensive:

* it always writes exactly one ``{status, error, payload}`` envelope back
  through the return channel, including when the collector raises;
* it never lets an exception escape into the target, because the interrupted
  code would otherwise see an exception it cannot explain;
* every name it binds is prefixed with ``_pidprobe_`` and deleted again when
  the script finishes, so the injection cannot disturb the target's namespace
  even if CPython runs the script in the target's own module globals.

The channel description (:class:`ChannelSpec`) lives here rather than in
``_channel`` so the dependency runs one way: ``_channel`` imports ``_inject``.
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass
from enum import Enum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

SCRIPT_FILENAME = "pidprobe_inject.py"
"""Name used for the generated script file inside a caller-owned directory."""

NAME_PREFIX = "_pidprobe_"
"""Prefix applied to every name the generated script binds."""

_COLLECTOR_INDENT = " " * 8
_WRITE_BACK_INDENT = " " * 4


class ChannelKind(Enum):
    """How the injected script hands its envelope back to pidprobe."""

    UNIX_SOCKET = "unix_socket"
    TEMPFILE = "tempfile"


@dataclass(frozen=True, slots=True)
class ChannelSpec:
    """Everything the injected script needs to reach the return channel.

    Attributes:
        kind: Transport the generated script must use.
        path: Socket path (``UNIX_SOCKET``) or result file path (``TEMPFILE``).
        timeout_seconds: Upper bound for the target's own write-back attempt,
            so a stuck channel cannot block the target forever.
    """

    kind: ChannelKind
    path: str
    timeout_seconds: float


_SCRIPT_TEMPLATE = '''\
# Generated by pidprobe -- executed inside the target process via
# sys.remote_exec. Every binding is namespaced with the {prefix} prefix and
# removed again, so the target's module namespace is left as it was found.


def _pidprobe_main():
    import json as _pidprobe_json
    import sys as _pidprobe_sys
    import traceback as _pidprobe_traceback
{extra_imports}

    # Frame of _pidprobe_main itself; its f_back is this script's module
    # frame, and *that* frame's caller is the target code the injection
    # interrupted. The pair marks where pidprobe ends and the target begins.
    _pidprobe_root = _pidprobe_sys._getframe()

    def _pidprobe_target_frames():
        """Return {{thread_id: frame}} without pidprobe's own frames.

        sys._current_frames() reports the frame that is executing *right
        now*, which on this thread is the injected script itself. Dropping
        every frame up to and including this script's module frame yields
        the frame the injection interrupted, i.e. real target code.
        """
        _pidprobe_own = set()
        _pidprobe_frame = _pidprobe_sys._getframe()
        while _pidprobe_frame is not None:
            _pidprobe_own.add(id(_pidprobe_frame))
            if _pidprobe_frame is _pidprobe_root:
                if _pidprobe_frame.f_back is not None:
                    _pidprobe_own.add(id(_pidprobe_frame.f_back))
                break
            _pidprobe_frame = _pidprobe_frame.f_back
        _pidprobe_frames = {{}}
        for _pidprobe_tid, _pidprobe_top in _pidprobe_sys._current_frames().items():
            while _pidprobe_top is not None and id(_pidprobe_top) in _pidprobe_own:
                _pidprobe_top = _pidprobe_top.f_back
            if _pidprobe_top is not None:
                _pidprobe_frames[_pidprobe_tid] = _pidprobe_top
        return _pidprobe_frames

    def _pidprobe_error_envelope():
        _pidprobe_exc = _pidprobe_sys.exc_info()[1]
        return {{
            "status": "error",
            "error": {{
                "type": type(_pidprobe_exc).__name__,
                "message": str(_pidprobe_exc),
                "traceback": _pidprobe_traceback.format_exc(),
            }},
            "payload": None,
        }}

    def _pidprobe_collect():
        payload = None
{collector}
        return payload

    # Any collector failure -- including a payload that will not serialize --
    # has to come back as an error envelope; a silent target would leave the
    # prober waiting for its hard timeout with nothing to report.
    try:
        _pidprobe_data = _pidprobe_json.dumps(
            {{"status": "ok", "error": None, "payload": _pidprobe_collect()}}
        ).encode("utf-8")
    except BaseException:
        _pidprobe_data = _pidprobe_json.dumps(_pidprobe_error_envelope()).encode("utf-8")

{write_back}


# The target process must survive whatever happens above -- a failed write
# back is pidprobe's problem, never the target's.
try:
    _pidprobe_main()
except BaseException:
    pass
try:
    del _pidprobe_main
except BaseException:
    pass
'''

_SOCKET_IMPORT = "    import socket as _pidprobe_socket"
_TEMPFILE_IMPORT = "    import os as _pidprobe_os"

_SOCKET_WRITE_BACK = """\
_pidprobe_sock = _pidprobe_socket.socket(
    _pidprobe_socket.AF_UNIX, _pidprobe_socket.SOCK_STREAM
)
try:
    _pidprobe_sock.settimeout({timeout!r})
    _pidprobe_sock.connect({path!r})
    _pidprobe_sock.sendall(_pidprobe_data)
finally:
    _pidprobe_sock.close()
"""

# Write to a sibling temp file and rename: the prober polls for the final
# path, so it must never observe a half-written envelope.
_TEMPFILE_WRITE_BACK = """\
_pidprobe_tmp = {path!r} + ".tmp"
_pidprobe_fd = _pidprobe_os.open(
    _pidprobe_tmp,
    _pidprobe_os.O_WRONLY | _pidprobe_os.O_CREAT | _pidprobe_os.O_TRUNC,
    0o600,
)
try:
    _pidprobe_os.write(_pidprobe_fd, _pidprobe_data)
finally:
    _pidprobe_os.close(_pidprobe_fd)
_pidprobe_os.replace(_pidprobe_tmp, {path!r})
"""


def _write_back_source(spec: ChannelSpec) -> tuple[str, str]:
    """Return the import line and write-back block for a channel.

    Args:
        spec: Channel the generated script must write to.

    Returns:
        A tuple of ``(import_line, write_back_block)``, both already
        indented to sit inside the generated ``_pidprobe_main`` function.
    """
    match spec.kind:
        case ChannelKind.UNIX_SOCKET:
            extra_import = _SOCKET_IMPORT
            block = _SOCKET_WRITE_BACK.format(
                path=spec.path,
                timeout=spec.timeout_seconds,
            )
        case ChannelKind.TEMPFILE:
            extra_import = _TEMPFILE_IMPORT
            block = _TEMPFILE_WRITE_BACK.format(path=spec.path)
    return extra_import, textwrap.indent(block, _WRITE_BACK_INDENT)


def build_injection_script(collector_source: str, spec: ChannelSpec) -> str:
    """Render the full script to inject into a target process.

    Args:
        collector_source: Python source executed inside the target. It runs
            in its own function scope and must assign a JSON-serializable
            ``dict`` to the name ``payload``. The helper
            ``_pidprobe_target_frames()`` is in scope and returns the target's
            frames with pidprobe's own frames stripped out.
        spec: Return channel the script writes its envelope to.

    Returns:
        Standalone, standard-library-only Python source.
    """
    body = textwrap.dedent(collector_source).strip("\n")
    extra_import, write_back = _write_back_source(spec)
    return _SCRIPT_TEMPLATE.format(
        prefix=NAME_PREFIX,
        extra_imports=extra_import,
        collector=textwrap.indent(body, _COLLECTOR_INDENT),
        write_back=write_back,
    )


def write_injection_script(
    collector_source: str,
    spec: ChannelSpec,
    directory: Path,
) -> Path:
    """Render the injection script and write it into *directory*.

    :func:`sys.remote_exec` reads the script from disk in the target process,
    so the file must stay readable until the target answers.

    Args:
        collector_source: Python source executed inside the target; see
            :func:`build_injection_script`.
        spec: Return channel the script writes its envelope to.
        directory: Existing directory owned by the caller, who is also
            responsible for removing it.

    Returns:
        Path of the generated script.
    """
    script_path = directory / SCRIPT_FILENAME
    script_path.write_text(build_injection_script(collector_source, spec), "utf-8")
    return script_path
